[build]
  command = "npm run build"
  publish = "out"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.1.0"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
  framework = "next"
  targetPort = 3000

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
